# Generated by Django 4.1 on 2023-01-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0003_user_pic_trainerdetails_customerdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdetails",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="workout.customer"
            ),
        ),
        migrations.AlterField(
            model_name="trainerdetails",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainerdetails",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="workout.trainer"
            ),
        ),
    ]
