# Generated by Django 4.1 on 2023-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0005_alter_customerdetails_user_alter_trainerdetails_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdetails",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
