# Generated by Django 4.1 on 2023-01-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0006_customerdetails_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerBiometrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("body_weight", models.IntegerField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_stats",
                        to="workout.customerdetails",
                    ),
                ),
            ],
        ),
    ]
