# Generated by Django 4.1 on 2023-01-08 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0007_customerbiometrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerbiometrics",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
