# Generated by Django 4.1 on 2023-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0008_alter_customerbiometrics_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerbiometrics",
            name="body_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerdetails",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
