# Generated by Django 4.1 on 2023-01-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0009_alter_customerbiometrics_body_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbiometrics",
            name="body_fat_p",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerbiometrics",
            name="muscle_mass",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
