# Generated by Django 4.1 on 2023-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0010_customerbiometrics_body_fat_p_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("muscle", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="customerbiometrics",
            name="body_fat_p",
            field=models.FloatField(blank=True, null=True, verbose_name="Body fat"),
        ),
    ]
