# Generated by Django 4.1 on 2023-01-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0013_workout_workoutset"),
    ]

    operations = [
        migrations.RemoveField(model_name="workoutset", name="exercise",),
        migrations.RemoveField(model_name="workoutset", name="workout",),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_nr", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workout.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workout.workout",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workoutset",
            name="workout_exercise",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts_sets",
                to="workout.workoutexercise",
            ),
            preserve_default=False,
        ),
    ]
