# Generated by Django 4.1 on 2023-11-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0016_workoutexercise_workoutset"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="scheduled_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workoutset",
            name="workout_exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_sets",
                to="workout.workoutexercise",
            ),
        ),
    ]
