# Generated by Django 4.1 on 2023-12-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0018_workout_workout_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="workout", name="scheduled_for",),
    ]
