# Generated by Django 4.1 on 2023-12-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0019_remove_workout_scheduled_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdetails",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="workout.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerdetails",
            name="trainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer",
                to="workout.trainer",
            ),
        ),
    ]
