# Generated by Django 4.1 on 2023-12-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0020_customerdetails_customer_customerdetails_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdetails",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer",
                to="workout.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerdetails",
            name="trainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="workout.trainer",
            ),
        ),
    ]
