# Generated by Django 4.1 on 2023-12-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0021_alter_customerdetails_customer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerBiometrics", new_name="CustomerBiometric",
        ),
        migrations.RenameModel(old_name="CustomerDetails", new_name="CustomerDetail",),
        migrations.RenameModel(old_name="TrainerDetails", new_name="TrainerDetail",),
    ]
