# Generated by Django 4.1 on 2023-12-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0022_rename_customerbiometrics_customerbiometric_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customerdetail", name="customer",),
    ]
